SELECT
OrderID,
ProductID,
Sales,
FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales) LowestSale,
Sales-FIRST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales) SalesDiff,
Sales-LAST_VALUE(Sales) OVER(PARTITION BY ProductID ORDER BY Sales ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) Salesdiff
FROM Sales.Orders
